version: '3'
services:
  postgresql:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  watcher:
    build:
      context: .
      dockerfile: Dockerfile
    user: "root:sudo"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app/
    command: sh -c "pipenv install && PYTHONPATH=. pipenv run python3 ./jmc/frugal/watcher/__main__.py"
    depends_on:
      - postgresql
    network_mode: "service:postgresql"