version: '3'
services:
  postgresql:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  watcher:
    build:
      context: .
      dockerfile: Dockerfile